name 'cens-backup'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures cens-backup'
long_description 'Installs/Configures cens-backup'
version '0.2.10'

depends 'zfs'
depends 'backup'
depends 'build-essential'
depends 'sanoid'
